FROM ruby:3.1.3-alpine

ENV APP_PATH /var/app
ENV BUNDLE_VERSION 2.4.1
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STOUT true
ENV RAILS_PORT 3000

COPY ./docker-entrypoint.sh /usr/local/bin/entrypoint.sh
COPY ./test-docker-entrypoint.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && chmod +x /usr/local/bin/test-entrypoint.sh

# setup deps for rails
RUN apk -U add --no-cache \
  bash \
  build-base \
  git \
  postgresql-dev \
  postgresql-client \
  libxml2-dev \
  libxslt-dev \
  nodejs \
  yarn \
  imagemagick \
  tzdata \
  less \
  && rm -rf /var/cache/apk/* \
  && mkdir -p $APP_PATH 


RUN gem install bundler --version "$BUNDLE_VERSION" \
  && rm -rf $GEM_HOME/cache/*

# navigate to app directory
WORKDIR $APP_PATH

EXPOSE $RAILS_PORT

ENTRYPOINT [ "bundle", "exec" ]
