version: '3.3'
networks:
  development:
  test:
volumes:
  gem_cache:
services:
  db:
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:12.5-alpine
    networks:
      - development
      - test
    ports:
      - 5432:5432
    volumes:
      - ./tmp/storage:/var/lib/postgresql/data

  time_manager_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
    container_name: time_manager
    depends_on:
      - db
    entrypoint: entrypoint.sh
    environment:
      RAILS_ENV: development
    networks:
      - development
    ports:
      - '3000:3000'
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app
      - gem_cache:/usr/local/bundle/gems

  time_manager_test:
    command: ['rails', '-v']
    container_name: time_manager_test
    depends_on:
      - db
    entrypoint: test-entrypoint.sh
    environment:
      RAILS_ENV: test
    image: time_manager-time_manager_app
    networks:
      - test
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app
      - gem_cache:/usr/local/bundle/gems
